version: '3'
services:

  canceled-app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: canceled-app
    image: digitalocean.com/flask-python:3.6
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_USERNAME: canceled-app
      MONGODB_PASSWORD: 5i0ZOoLVUwJejfiN
      MONGODB_HOSTNAME: canceled-f4rau.mongodb.net/test?retryWrites=true&w=majority
    volumes:
      - appdata:/var/www
    networks:
      - frontend

  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: digitalocean.com/webserver:latest
    container_name: webserver
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "true"
      SERVICE_NAME: "webserver"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - canceled-app
    networks:
      - frontend

networks:
  frontend:
    driver: bridge

volumes:
  appdata:
    driver: local
  nginxdata:
    driver: local
